server:
  port: 8080
spring:
  application:
    name: ems
  #数据库连接配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ems
    username: root
    password: 123456

#mybatis配置
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

#日志配置
logging:
  level:
    root: INFO
    com.yeyu: DEBUG
